/*! 
 * \file    CoImageDef.h
 * \ingroup base
 * \brief   Ãùº¬¼¿»õË¾ Ì¡ÂÙ ¶ë¿Íµá´ÉË¾ ¼³Ì©ÂÜ.
 * \author  ±®½èË§
 */

#ifndef _COIMAGEDEF_H_
#define _COIMAGEDEF_H_

#include "CoImageCFG.h"

#if CVLIB_IMG_SUPPORT_JP2 || CVLIB_IMG_SUPPORT_JPC || CVLIB_IMG_SUPPORT_PGX || CVLIB_IMG_SUPPORT_PNM || CVLIB_IMG_SUPPORT_RAS
 #define CVLIB_IMG_SUPPORT_JASPER 1
#else
 #define CVLIB_IMG_SUPPORT_JASPER 0
#endif

#if CVLIB_IMG_SUPPORT_DSP
#undef CVLIB_IMG_SUPPORT_TRANSFORMATION
 #define CVLIB_IMG_SUPPORT_TRANSFORMATION 1
#endif

#if CVLIB_IMG_SUPPORT_TRANSFORMATION || CVLIB_IMG_SUPPORT_TIF || CVLIB_IMG_SUPPORT_TGA || CVLIB_IMG_SUPPORT_BMP || CVLIB_IMG_SUPPORT_WINDOWS
 #define CVLIB_IMG_SUPPORT_BASICTRANSFORMATIONS 1
#endif

#if CVLIB_IMG_SUPPORT_DSP || CVLIB_IMG_SUPPORT_TRANSFORMATION
#undef CVLIB_IMG_SUPPORT_INTERPOLATION
 #define CVLIB_IMG_SUPPORT_INTERPOLATION 0
#endif

#if CVLIB_IMG_SUPPORT_WINCE
 #undef CVLIB_IMG_SUPPORT_WMF
 #define CVLIB_IMG_SUPPORT_WMF 0
 #undef	CVLIB_IMG_SUPPORT_WINDOWS
 #define	CVLIB_IMG_SUPPORT_WINDOWS 0
#endif

#ifndef WIN32
 #undef CVLIB_IMG_SUPPORT_WINDOWS
 #define CVLIB_IMG_SUPPORT_WINDOWS 0
#endif

#endif //_COIMAGEDEF_H_


